---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp -R * $DEPLOYPATH
    # Proteção de arquivos sensíveis após o deploy
    - /bin/chmod 755 $DEPLOYPATH/api
    - /bin/chmod 644 $DEPLOYPATH/api/*.php
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
